version: '3.8'

services:
  # React Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

  # FastAPI Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    environment:
      - ENVIRONMENT=development
      - RELOAD=true