services:
  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api

  # React Frontend
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
      target: development
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://localhost/api
      - NODE_ENV=development
      - DISABLE_HTTPS=true
    depends_on:
      - api

  # FastAPI Backend
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../apps/api:/app
    environment:
      - ENVIRONMENT=development
      - RELOAD=true