services:
  - type: web
    name: motion-detector-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: ENVIRONMENT
        value: production