services:
  - type: web
    name: motion-detector-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://feature-render-deployment.motion-detector.pages.dev,https://motion-detector.pages.dev,http://localhost:5173"
      - key: ENVIRONMENT
        value: production